parameters:
#    cody_landing_page.example.class: Cody\LandingPageBundle\Example

services:
#    cody_landing_page.example:
#        class: %cody_landing_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
